### ISSUE TITLE
Automated PE selection for active messages

### ISSUE THREAD

**Issue by wjhorne** [pnnl/lamellar-runtime#19]
Hi,

This is probably a super basic question but is it currently possible to submit an active message and allow the runtime to intelligently select a PE to accept/run the message rather than selecting the PE yourself? I ran into a case with a pretty sporadic load that isn't simple to pick a suitable PE and it would be nice to avoid doing so.

**Comment by rdfriese** [comment]
Hi,

Unfortunately, we currently do not support automatic task placement/distributed load balancing yet. (Although this is a feature I would to have in the future!)

In the use cases I've encounter, e.g. working with non uniform graphs, I've generally have had to do some pre processing to help ensure the data is as evenly distributed as possible, but this has had to happen at the user side unfortunately.

Another option that may be viable for you if all the data is packaged with your active messages (rather than sending active messages to where the data sits) is to simply randomize the PE where AM's execute?

**Comment by wjhorne** [comment]
No worries. I'll go with a randomized solution and switch over if automated task placement makes it in
