### ISSUE TITLE
LamellarWorldBuilder::new().build() and assert failure

### ISSUE THREAD

**Issue by defghij** [pnnl/lamellar-runtime#22]
Given the following code:
```Rust
// lib.rs
#[cfg(test)]
pub mod test {
    #[test]
    fn lamellar_fails() {
        let world = lamellar::LamellarWorldBuilder::new().build();
        assert_eq!(0,2);
    }
   
    #[test]
    fn tautology() {
        assert_eq!(0,0);
    }
}

// main.rs
fn main() { }
```

One gets the following errors with `cargo test lamellar_fails`
```
running 1 test
fi_domain(): /path/to/project/target/debug/build/rofisys-<hash>/out/rofi_src/transport.c:607, ret=-61 (No data available) [0]
error: test failed, to return pass `--lib`

Caused by:
    process didnt exit succuessfully: `/path/to/project/target/debug/deps/test-<hash>` (signal: 11, SIGSEV: invalid memory reference)
```

and with `srun -N <num_pes> --mpi=pmi2 /path/to/project/target/debug/deps/test-<hash> lamellar_fails`
```
Running 1 test
...
<project>-<hash>: prov/util/src/util_mem_monitor.c:84: ofi_monitor_cleanup: Assertion `dlist_empty(&monitor->list)`  failed.
...
srun: Terminating job step...
```
 
Is this expected? I'm trying to create some tests for an application and this issue is corrupting cargo's test framework. When running other tests individually the output from `cargo test` is as one would expect.  However, if a test similar to `tautology`  above is included in the suite then output is truncated as shown above such that `RUST_BACKTRACE=1 cargo test` provides no backtrace for this test or any other that may fail.

When running with `local` a similar issue exists but only states that the process did not exit correctly.

**Comment by rdfriese** [comment]
Thanks for submitting the issue! 

To help get a better idea of what may be going wrong could you let me know what versions of

1. Lamellar ( are you using github, which branch? or crates.io, which version?) 
2. ROFI - Did you install Rofi yourself? ( Lamellar is also able to install the latest version manually, but there may be an issue with that I didnt catch)
3. Libfabrics


Starting with the second issue, this actually appears to me that it got through the test but it failed when trying to shutdown, this used to happen in an older version of ROFI (that I thought we had fixed, but given our limited testing environments it may behave incorrectly on other systems still). I don't expect it will make a difference, but have you been able to create a normal binary (instead of a test) and have that successfully complete?

With respect to the first error,  I think there are a few issues: the first of which is when running with ROFI, it currently relies on libpmi2  to help establish communication between different PEs (even if we are only using a single PE), when being invoked via "cargo test" the appropriate libraries and Environment Variables do not exist, so the error provided is expected unfortunately.

How I have gotten around this is the essentially have my test function be a wrapper that will call a script that launches my actual test. This can be seen in the "tests" folder of the repository (we use macros fairly heavily to create our tests though so it may not be straight forward to follow, if you want more details on how we set this up please let me know).

What is not expected I don't think is the fact that it still failed with using the Local lamellar, I will try to reproduce this behavior on my end and hopefully see if I can figure out the issue.

A few other things related to Cargo Test that you may find helpful (or you may already know about):
I believe by default, Cargo is set to "fail-fast" meaning it will stop after the first error (across all threads), you can try `cargo test --no-fail-fast` and this will allow some of the tests to keep executing, but I believe any tests that were scheduled to execute on a thread where a test fails will not execute.

**Comment by rdfriese** [comment]
tCan you replace your current lamellar import in Cargo.toml with: 
`lamellar = { git = "https://github.com/pnnl/lamellar-runtime", branch = "22-lamellarworldbuildernewbuild-and-assert-failure" }`

and then do a `cargo test` 

This should hopefully work for the local lamellae,  the Rofi lamellae will take some extra work due to the distributed nature

**Comment by defghij** [comment]
Great; thanks! I'll have to ask to get the version updated to capture the new branch and get back to you on whether it worked.

A bit late but here is the information you asked for:
- Libfabric: 1.12.0
- ROFI: 0.1 
  - (as indicated by the rofi `README.md`)
- lamellar branch: dev
  - features: "enable-rofi"

**Comment by rdfriese** [comment]
Pushed a new commit that hopefully will handle panics with the rofi-lamellae now to (although its a bit harder to test in the distributed environment, so there may be some instances where it wont exit gracefully)

**Comment by defghij** [comment]
Tried the new branch. Below is a reproducer of what we are seeing when we use the new branch.
```
error[E0368]: binary assignment operation '+=' cannot be applied to `MyStruct`
-->src/main.rs:4:5
  |
4 |   #[lamellar::AmData(Debug, Default, ArrayOps, PartialEq, PartialOrd)]
  |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot use '+= on type `MyStruct
  |
note: an implementation of `AddSign<_> might be missing for `MyStruct`
--> src/main.rs4:5
  |
4 |  #[lamellar::AmData(Debug, Default, ArrayOps, PartialEq, PartialOrd)]
  |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Must implement `AddSign<_>`
note: the following trait must be implemented
...
```
The error above is repeated for the following traits:  SubAssign<_>, MulAssign<_>, DivAssign<_>, std::ops::Sub<_>

```Toml
[package]
name = "lamellar_test"
version = "0.1.0"
edition = "2021"

[dependencies]
lamellar = { git = "https://github.com/pnnl/lamellar-runtime", branch = "22-lamellarworldnewbuild-and-assert-faulure"
```
```Rust
use lamellar::array::prelude::*;

mod my_structs{
  #[lamellar::AmData(Debug, Default, ArrayOps, PartialEq, PartialOrd)]
  pub struct MyStruct {
    pub val: u32
  } impl MyStruct {
    pub fn new() -> Self {
      Self { val: 0 }
    }
  }
fn main() {
  use crate::my_struct::MyStruct;
 
  let world = lamellar::LamellarWorldBuilder::new().build();
  let my_pe = world.my_pe();
  let array_size: usize = 5_000;
  let arr = AtomicArray::<MyStruct>::new(&world, array_size,  Distribution::Block);
  assert!(my_pe < array_size);
  arr.block_on(arr.store(my_pe, MyStruct{ val: (my_pe+1) as u32}));
  println!("don on PE {}", my_pe);
}
```

**Comment by rdfriese** [comment]
This looks related to issues #24 and #25, the short answer is the branch for this issue (#22) originally patched the master branch, the dev branch already had a fix for the issue you were seeing above.  I went ahead and rebased the issue branch based on dev, if you retry to build your code again after pulling it should hopefully compile.


I think it is probably worth discussing the long answer and when and why this issue same may show up when trying to compile in the future.

Essentially the goal is to allow LamellarArrays to support arbitrary user defined data types, with the specific types of operations supported by the LamellarArray, controlled by the traits implemented on the user defined data type.

In your example the only operation you perform is a `store.` This should require no additional traits to be implemented for your `MyStuct` data type (other than the ones automatically derived by the `#[AmData(ArrayOps)]` macro. The reason you were getting the errors you did was because we were being overly restrictive on our trait bounds when deriving all the needed "glue" code in the `#[AmData(ArrayOps)]` macro. The dev branch (and consequently the new commit of the issue #22 branch) have relaxed this constraint.

Now lets say instead of a `store` you instead of a store  you want to do some arithmetic operation like a `fetch_add`, you will once again encounter the errors about `AddAssign, SubAssign, MulAssign, DivAssign, etc`, this is as intended as you would receive the same error from the Rust compiler if you simply tried to do the following:
```rust
let a = MyString{val: 0};
let mut b = MyString{val:1};
b += a;
```
In the case above you would only receive a single error about AddAssign.  For Lamellar, we currently group all the arithmetic operations into a single Supertrait which requires all the "*Assign" traits to be implemented on the user defined type.
This is discussed a bit in the [ArrayOps](https://docs.rs/lamellar/latest/lamellar/array/derive.ArrayOps.html) documentation, but that page is neither easy to find, nor is it up-to-date with the fixes and changes in the dev branch (it is relevant to master though).  The following example also highlights this: [ArrayOps Example](https://github.com/pnnl/lamellar-runtime/blob/22-lamellarworldbuildernewbuild-and-assert-failure/examples/array_examples/array_ops.rs)

The following is a working example performing a `fetch_add`, the key thing to notice is that in addition to implementing the "Assign" traits, you must also pass `Arithmetic` to the `ArrayOps` attribute e.g. `#[AmData(ArrayOps(Arithmetic))]` otherwise the application will compile  but will encounter a runtime error regarding "FetchAdd", I am working on some improvements to address this in issue #25 which will not allow the application to compile, as well as hopefully provided better compiler errors why it didn't compile
```rust
use lamellar::array::prelude::*;

mod my_structs{
  #[lamellar::AmData(Debug, Default, ArrayOps(Arithmetic), PartialEq, PartialOrd)]
  pub struct MyStruct {
    pub val: u32
  } 
  impl MyStruct {
    pub fn new() -> Self {
      Self { val: 0 }
    }
  }

  impl std::ops::AddAssign for MyStruct {
    fn add_assign(&mut self, rhs: Self) {
      self.val += rhs.val
    }
  }

  impl std::ops::SubAssign for MyStruct {
    fn sub_assign(&mut self, rhs: Self) {
      self.val -= rhs.val
    }
  }

  impl std::ops::MulAssign for MyStruct {
    fn mul_assign(&mut self, rhs: Self) {
      self.val *= rhs.val
    }
  }

  impl std::ops::DivAssign for MyStruct {
    fn div_assign(&mut self, rhs: Self) {
      self.val /= rhs.val
    }
  }

  impl std::ops::RemAssign for MyStruct {
    fn rem_assign(&mut self, rhs: Self) {
      self.val %= rhs.val
    }
  }
}

fn main() {
  use crate::my_structs::MyStruct;
 
  let world = lamellar::LamellarWorldBuilder::new().build();
  let my_pe = world.my_pe();
  let array_size: usize = 5_000;
  let arr = AtomicArray::<MyStruct>::new(&world, array_size,  Distribution::Block);
  assert!(my_pe < array_size);
  arr.block_on(arr.store(my_pe, MyStruct{ val: (my_pe+1) as u32}));
  let old_val = arr.block_on(arr.fetch_add(my_pe,MyStruct{ val: (my_pe+1) as u32}));
  let new_val = arr.block_on(arr.load(my_pe));
  println!("old val {old_val:?}");
  println!("new val {new_val:?}");
  println!("done on PE {}", my_pe);
}
```

**Comment by rdfriese** [comment]
see #25 can reopen if errors still occur
