### ISSUE TITLE
How to run tests of Lamellar

### ISSUE THREAD

**Issue by bingao** [pnnl/lamellar-runtime#40]
Hi,

I would like to know how to run tests of Lamellar correctly. Should I simply run `cargo test`, or do I also need to set up some environment variables? Thank you.

Moreover, I guess the TEST section is missing in `README.md`. It is written "see TEST section below" before the section "HISTORY".

**Comment by rdfriese** [comment]
Thanks for bringing this to my attention about the README

Generally, at least on linux (I'm not sure if this works well on Mac or not), I typically do something like `cargo test --release `  
Internally, this will make use of the  `lamellar_run.sh` script to launch the tests using multiprocessed shared memory mode (but only on a single compute node, not distributed).

This can take a very long time as the tests themselves use a lot of macro expansions resulting in  over 5000 individual tests to be executed.

I have found that it is easier to begin experimenting with the Examples (which the Readme should be reasonably up-to-date for!), rather than the tests.

Let me know if you have any issues an I will be glad to help!

**Comment by bingao** [comment]
Thank you, @rdfriese I think will first try `cargo test --release` to check if my building of Lamellar works well and correctly on our Linux clusters.

Then I will investigate those examples to be familiar with Lamellar.
